- name: Install python
  ansible.builtin.apt:
    name:
    - python-dev
    - python-pip
    - python3-dev
    - python3-pip
    state: present

- name: Install pipx
  ansible.builtin.pip:
    name:
    - virtualenv
    - setuptools