- name: Install git
  ansible.builtin.include_role:
    name: git

- name: Install github3.py with pip
  ansible.builtin.pip:
    name: github3.py
    state: present
    # install_deps: yes

- name: "Get Latest Release from Github"
  community.general.github_release:
    user: cli
    repo: cli
    action: latest_release
    token: "{{ github_token }}"

- name: Download Binary
  ansible.builtin.unarchive:
    # src: https://github.com/cli/cli/releases/download/{{release.tag}}/gh_{{release.tag[1:]}}_linux_amd64.tar.gz
    src: https://github.com/cli/cli/releases/download/v2.11.3/gh_2.11.3_linux_amd64.tar.gz
    dest: /tmp
    remote_src: true

- name: Install Binary
  become: yes
  become_user: root
  ansible.builtin.copy:
    # src: /tmp/gh_{{release.tag[1:]}}_linux_amd64/bin/gh
    src: /tmp/gh_2.11.3_linux_amd64/bin/gh
    dest: "/usr/local/bin"
    mode: a+x
    owner: morpheush3x

# - name: Setup SSH private key
# prompt, utiliser la même que d'hab ou en générer une ...