---

- name: Laptop
  hosts: laptop
  become: true
  become_user: morpheush3x

  vars_prompt:
    - name: github_token
      prompt: "What is your GitHub Token?"
      default: "{{ lookup('env','GITHUB_TOKEN') }}"
      private: yes

  roles:
    - apt
    - git
    - neovim
    - python
    - vcsh
    - zsh
    - gh
    - hacking