- name: Install python
  ansible.builtin.apt:
    name:
    - python-dev
    # - python-pip
    - python3-dev
    - python3-pip
    - python3-venv
    state: present

- name: Install pipx requierements
  ansible.builtin.pip:
    name:
    - virtualenv
    - setuptools
    - pipx

- name: Install pipx
  ansible.builtin.pip:
    name:
    - pipx
    extra_args: --user 