# From https://github.com/Fongshway/ansible-role-vcsh

- name: Install git
  ansible.builtin.include_role:
    name: git


- name: Install vcsh dependencies
  apt:
    name: "{{ item }}"
    state: present
  become: true
  with_items:
    - make
    - ruby-ronn
    - which
  state: present

- name: Clone vcsh repo
  git:
    repo: https://github.com/RichiH/vcsh.git
    version: master
    dest: /tmp/vcsh

- name: Install vcsh
  command: make install
  become: true
  args:
    chdir: /tmp/vcsh
    creates: /usr/bin/vcsh

# - name: Install my dotfiles 